DELETE http://localhost:8080/api/persons/1

###
POST http://localhost:8080/api/persons
Content-Type: application/json

{
    "name": "Ayush",
    "number": "85-05-050998"
}

###
POST http://localhost:8080/api/persons
Content-Type: application/json

{
    "name": "Ayush"
}
